"""MarketUpdate

Revision ID: 136abe5cb312
Revises: 9e13a335e2ef
Create Date: 2025-06-26 09:51:41.569951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '136abe5cb312'
down_revision: Union[str, None] = '9e13a335e2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_updates',
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.Column('reranked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('market_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_updates')
    # ### end Alembic commands ###
