"""added weight scores and chain of thoughts

Revision ID: 20614985e7f2
Revises: 77cdcd2f43d1
Create Date: 2025-07-29 10:13:21.942347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '20614985e7f2'
down_revision: Union[str, None] = '77cdcd2f43d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength_scores', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('relevance_scores', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('strength_chain', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('relevance_chain', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_rules', schema=None) as batch_op:
        batch_op.drop_column('relevance_chain')
        batch_op.drop_column('strength_chain')
        batch_op.drop_column('relevance_scores')
        batch_op.drop_column('strength_scores')

    # ### end Alembic commands ###
