"""added update col for 5 market data relevances

Revision ID: 30173029264d
Revises: ee21cdaaaa12
Create Date: 2025-07-24 11:18:56.240045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '30173029264d'
down_revision: Union[str, None] = 'ee21cdaaaa12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_data_relevances_recorded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_updates', schema=None) as batch_op:
        batch_op.drop_column('market_data_relevances_recorded_at')

    # ### end Alembic commands ###
