"""typo

Revision ID: 343f04868023
Revises: 69eea606f70b
Create Date: 2025-06-18 16:56:28.922999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '343f04868023'
down_revision: Union[str, None] = '69eea606f70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_time', sa.DateTime(), nullable=False))
        batch_op.drop_column('last_updated_timed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_timed', sa.DateTime(), nullable=False))
        batch_op.drop_column('last_updated_time')
    # ### end Alembic commands ###
