"""Add upper and lower bounds to index

Revision ID: 392053e5f354
Revises: a7f0e32a8395
Create Date: 2026-03-19 16:55:13.781018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '392053e5f354'
down_revision: Union[str, None] = 'a7f0e32a8395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upper_probability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lower_probability', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index', schema=None) as batch_op:
        batch_op.drop_column('lower_probability')
        batch_op.drop_column('upper_probability')

    # ### end Alembic commands ###
