"""clean migration

Revision ID: 3a7de0d36b89
Revises: 
Create Date: 2025-06-18 16:11:37.528942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3a7de0d36b89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_label_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_name')
    )
    op.create_table('market_relevance_score_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_name')
    )
    op.create_table('markets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Float(), nullable=False),
    sa.Column('unique_bettor_count', sa.Integer(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_liquidity', sa.Float(), nullable=False),
    sa.Column('outcome_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mechanism', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('last_updated_timed', sa.DateTime(), nullable=False),
    sa.Column('closed_time', sa.DateTime(), nullable=False),
    sa.Column('resolution_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_labels',
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_type_id'], ['market_label_types.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('market_id', 'label_type_id')
    )
    op.create_table('market_relevance_scores',
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_type_id', sa.Integer(), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['score_type_id'], ['market_relevance_score_types.id'], ),
    sa.PrimaryKeyConstraint('market_id', 'score_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_relevance_scores')
    op.drop_table('market_labels')
    op.drop_table('markets')
    op.drop_table('market_relevance_score_types')
    op.drop_table('market_label_types')
    # ### end Alembic commands ###
