"""add batch number to rules table

Revision ID: 45360a7086da
Revises: ebf3757c72f4
Create Date: 2025-08-01 17:21:10.572689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '45360a7086da'
down_revision: Union[str, None] = 'ebf3757c72f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_rules', schema=None) as batch_op:
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
