"""add id to the relevance scores

Revision ID: 627ba48b0518
Revises: c9cbecb6336a
Create Date: 2025-11-17 13:01:29.292587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '627ba48b0518'
down_revision: Union[str, None] = 'c9cbecb6336a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_relevance_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_market_relevance_scores_label_id", 'market_label_types', ['label_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_relevance_scores', schema=None) as batch_op:
        batch_op.drop_constraint("fk_market_relevance_scores_label_id", type_='foreignkey')
        batch_op.drop_column('label_id')

    # ### end Alembic commands ###
