"""adding scores to relevance scores

Revision ID: 77cdcd2f43d1
Revises: c85731f79c44
Create Date: 2025-07-25 16:46:40.798024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '77cdcd2f43d1'
down_revision: Union[str, None] = '30173029264d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_relevance_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scores', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_relevance_scores', schema=None) as batch_op:
        batch_op.drop_column('scores')

    # ### end Alembic commands ###
