"""update timestamp variable names

Revision ID: 7dfd67c4a227
Revises: 026f44b3d2d5
Create Date: 2025-06-16 21:55:17.801034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7dfd67c4a227'
down_revision: Union[str, None] = '026f44b3d2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('markets', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.add_column('markets', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('markets', 'last_updated')
    op.drop_column('markets', 'close_time')
    op.drop_column('markets', 'created_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('created_time', sa.DATETIME(), nullable=False))
    op.add_column('markets', sa.Column('close_time', sa.DATETIME(), nullable=True))
    op.add_column('markets', sa.Column('last_updated', sa.DATETIME(), nullable=False))
    op.drop_column('markets', 'updated_at')
    op.drop_column('markets', 'closed_at')
    op.drop_column('markets', 'created_at')
    # ### end Alembic commands ###
