"""Dropped scores and index to question links, added labeling info dump, will change the label names and IDs

Revision ID: b5318e39aee1
Revises: 56d4b33aaded
Create Date: 2025-11-17 10:59:55.072356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b5318e39aee1'
down_revision: Union[str, None] = '56d4b33aaded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels_info_dump',
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('initial', 'final', name='labeltype'), nullable=False),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('market_id')
    )
    with op.batch_alter_table('labels_info_dump', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labels_info_dump_type'), ['type'], unique=False)

    op.drop_table('index_question_label_links')
    with op.batch_alter_table('market_relevance_scores', schema=None) as batch_op:
        batch_op.drop_column('scores')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_relevance_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scores', sa.VARCHAR(), nullable=True))

    op.create_table('index_question_label_links',
    sa.Column('index_question_id', sa.INTEGER(), nullable=False),
    sa.Column('label_type_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['index_question_id'], ['index_questions.id'], ),
    sa.ForeignKeyConstraint(['label_type_id'], ['market_label_types.id'], ),
    sa.PrimaryKeyConstraint('index_question_id', 'label_type_id')
    )
    with op.batch_alter_table('labels_info_dump', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labels_info_dump_type'))

    op.drop_table('labels_info_dump')
    # ### end Alembic commands ###
