"""added index id col to rules

Revision ID: b7150401416c
Revises: 627ba48b0518
Create Date: 2025-11-20 08:13:52.316974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b7150401416c'
down_revision: Union[str, None] = '627ba48b0518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_rules', schema=None) as batch_op:
        batch_op.drop_column('index_id')

    # ### end Alembic commands ###
