"""added full market update col

Revision ID: bfa3a3bae344
Revises: 136abe5cb312
Create Date: 2025-06-27 14:05:52.033072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'bfa3a3bae344'
down_revision: Union[str, None] = '136abe5cb312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_market_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_updates', schema=None) as batch_op:
        batch_op.drop_column('full_market_at')

    # ### end Alembic commands ###
