"""fresh_migration

Revision ID: c0c97193ec83
Revises: 
Create Date: 2025-06-20 14:43:01.486021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c0c97193ec83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_label_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_name')
    )
    op.create_table('market_relevance_score_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_name')
    )
    op.create_table('markets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Float(), nullable=False),
    sa.Column('unique_bettor_count', sa.Integer(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_liquidity', sa.Float(), nullable=False),
    sa.Column('outcome_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mechanism', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('last_updated_time', sa.DateTime(), nullable=False),
    sa.Column('closed_time', sa.DateTime(), nullable=True),
    sa.Column('resolution_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_bets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bet_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('order_amount', sa.Float(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('fills', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prob_before', sa.Float(), nullable=False),
    sa.Column('prob_after', sa.Float(), nullable=False),
    sa.Column('limit_prob', sa.Float(), nullable=True),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_api', sa.Boolean(), nullable=False),
    sa.Column('is_filled', sa.Boolean(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('is_redemption', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('liquidity_fee', sa.Float(), nullable=False),
    sa.Column('creator_fee', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_comments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reply_to_comment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_api', sa.Boolean(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('hidden_time', sa.DateTime(), nullable=True),
    sa.Column('edited_ime', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_labels',
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_type_id'], ['market_label_types.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('market_id', 'label_type_id')
    )
    op.create_table('market_relevance_scores',
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_type_id', sa.Integer(), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['score_type_id'], ['market_relevance_score_types.id'], ),
    sa.PrimaryKeyConstraint('market_id', 'score_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_relevance_scores')
    op.drop_table('market_labels')
    op.drop_table('market_comments')
    op.drop_table('market_bets')
    op.drop_table('markets')
    op.drop_table('market_relevance_score_types')
    op.drop_table('market_label_types')
    # ### end Alembic commands ###
