"""adding market rules and chain of thoughts cols

Revision ID: c85731f79c44
Revises: 30173029264d
Create Date: 2025-07-25 15:31:55.711973
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c85731f79c44'
down_revision: Union[str, None] = '30173029264d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create market_rules table
    op.create_table(
        'market_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('rule', sa.String(), nullable=False),
        sa.Column('readable_rule', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('strength_weight', sa.Float(), nullable=True),
        sa.Column('relevance_weight', sa.Float(), nullable=True),
        sa.Column('chain_of_thoughts', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # Create market_rule_links table
    op.create_table(
        'market_rule_links',
        sa.Column('market_id', sa.String(), nullable=False),
        sa.Column('rule_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
        sa.ForeignKeyConstraint(['rule_id'], ['market_rules.id'], ),
        sa.PrimaryKeyConstraint('market_id', 'rule_id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop tables in reverse order (due to foreign key constraints)
    op.drop_table('market_rule_links')
    op.drop_table('market_rules')

    # ### end Alembic commands ###