"""market labels tables

Revision ID: caff405581e2
Revises: 7dfd67c4a227
Create Date: 2025-06-16 22:12:50.873219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'caff405581e2'
down_revision: Union[str, None] = '7dfd67c4a227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_label_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_name')
    )
    op.create_table('market_labels',
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_type_id'], ['market_label_types.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('market_id', 'label_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_labels')
    op.drop_table('market_label_types')
    # ### end Alembic commands ###
