"""Added update table and update types

Revision ID: d41b3400d978
Revises: 9e13a335e2ef
Create Date: 2025-06-24 15:28:46.246130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'd41b3400d978'
down_revision: Union[str, None] = '9e13a335e2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_update_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('update_name')
    )
    op.create_table('market_updates',
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('update_type_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['update_type_id'], ['market_update_types.id'], ),
    sa.PrimaryKeyConstraint('market_id', 'update_type_id')
    )

    # Insert into market_update_types
    op.execute("""
            INSERT INTO market_update_types (update_name) VALUES
            ('classified')
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_updates')
    op.drop_table('market_update_types')
    # ### end Alembic commands ###
