"""add index table and linking table to rules

Revision ID: ebf3757c72f4
Revises: 20614985e7f2
Create Date: 2025-07-31 14:05:41.666592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'ebf3757c72f4'
down_revision: Union[str, None] = '20614985e7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_probability', sa.Float(), nullable=False),
    sa.Column('json_representation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_rule_links',
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['market_rules.id'], ),
    sa.PrimaryKeyConstraint('index_id', 'rule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_rule_links')
    op.drop_table('index')
    # ### end Alembic commands ###
