"""changing the update cols

Revision ID: ee21cdaaaa12
Revises: b64848614e7f
Create Date: 2025-07-24 11:02:30.606752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'ee21cdaaaa12'
down_revision: Union[str, None] = 'b64848614e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_relevance_scored_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('geo_relevance_scored_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('index_question_relevance_scored_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rule_eligibility_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('reranked_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reranked_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('rule_eligibility_at')
        batch_op.drop_column('index_question_relevance_scored_at')
        batch_op.drop_column('geo_relevance_scored_at')
        batch_op.drop_column('temp_relevance_scored_at')

    # ### end Alembic commands ###
