"""update trigger for markets

Revision ID: f2a895a51c71
Revises: fec7f2b25f93
Create Date: 2025-06-17 13:49:04.580882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'f2a895a51c71'
down_revision: Union[str, None] = 'fec7f2b25f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    CREATE TRIGGER IF NOT EXISTS update_markets_updated_at
    AFTER UPDATE ON markets
    FOR EACH ROW
    BEGIN
        UPDATE markets SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
    END;
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS update_markets_updated_at;')
    # ### end Alembic commands ###
