"""making indexquestion table and links. also made the relevance prompts table more general to just prompts

Revision ID: f55f4df01897
Revises: e0032747d8fe
Create Date: 2025-11-02 17:10:47.157621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'f55f4df01897'
down_revision: Union[str, None] = 'e0032747d8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_question_label_links',
    sa.Column('index_question_id', sa.Integer(), nullable=False),
    sa.Column('label_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['index_question_id'], ['index_questions.id'], ),
    sa.ForeignKeyConstraint(['label_type_id'], ['market_label_types.id'], ),
    sa.PrimaryKeyConstraint('index_question_id', 'label_type_id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sa.Enum('RELEVANCE', 'RULE', name='promptpurpose'), nullable=False),
    sa.Column('index_question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['index_question'], ['index_questions.question'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('relevance_prompts')
    with op.batch_alter_table('index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index_question', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.create_foreign_key("fk_index_index_question", 'index_questions', ['index_question'], ['question'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index', schema=None) as batch_op:
        batch_op.drop_constraint("fk_index_index_question", type_='foreignkey')
        batch_op.drop_column('index_question')

    op.create_table('relevance_prompts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prompt', sa.VARCHAR(), nullable=False),
    sa.Column('label_type_id', sa.INTEGER(), nullable=False),
    sa.Column('index_question', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['label_type_id'], ['market_label_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prompts')
    op.drop_table('index_question_label_links')
    op.drop_table('index_questions')
    # ### end Alembic commands ###
