"""market ranker tables

Revision ID: fec7f2b25f93
Revises: caff405581e2
Create Date: 2025-06-17 13:47:52.580826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fec7f2b25f93'
down_revision: Union[str, None] = 'caff405581e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_relevance_score_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_name')
    )
    op.create_table('market_relevance_scores',
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_type_id', sa.Integer(), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['score_type_id'], ['market_relevance_score_types.id'], ),
    sa.PrimaryKeyConstraint('market_id', 'score_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_relevance_scores')
    op.drop_table('market_relevance_score_types')
    # ### end Alembic commands ###
